name: Rust metar-rs Test

on:
  push:
  schedule:
    - cron: '*/30 9-15 * * 1-5'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo run
