name: metar-rs Automated Testing

on:
  push:
  schedule:
    - cron: '*/30 9-15 * * 1-5'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Update
        run: cargo update
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo run
